---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом в решении задач
  - Пользователи должны иметь возможность видеть написание кода друг у друга
  - Пользователи должны иметь возможность игра с ботом
  - Пользователи должны иметь возможность игра с другом по ссылке
  - Пользователи должны иметь возможность попасть в  рейтинг
  - Сайт должен быть удобным на мобильном устройстве
  - Пользователи должны иметь возможность зарегистрироваться
  - Пользователи должны иметь возможность войти в учетную запись
  - Пользователи должны видеть два редактора слева - свой редактор, справа - соперника
  - Пользователи должны иметь возможность выйти из игры, а может доиграть до конца
  - Пользователи должны иметь возможность продолжать играть если соперник  вылетел из игры
  - Пользователи должны иметь возможность в любой момент игры, пока она не закончена, переподключиться в игру
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появилась
  - Пользователи могут вдвоем выйти из игры тогда, игра считается полностью законченной и удаляется из памяти
  - Пользователям игры высвечивается модальное окно с надписью кто является победителем, когда один из игроков находит верное решение
non-functional:
  - Сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен уведомлять пользователей о появлении неожиданные проблемы/ошибки 
  - Сайт должен корректно отображаться на различных устройствах ( планшеты. смартфоны, ноутбуки, настольные компьютеры)
