---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом в решении задач
  - Пользователи должны иметь возможность видеть написание кода друг у друга
  - Пользователи должны иметь возможность игра с ботом
  - Пользователи должны иметь возможность игра с другом по ссылке
  - Пользователи должны иметь возможность попасть в  рейтинг
  - Сайт должен быть удобным на мобильном устройстве
non-functional:
  - Сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен уведомлять пользователей о появлении неожиданные проблемы/ошибки 
  - Сайт должен быть интуитивно понятным и легким в использовании, быстрым и безопасным для пользовательских данных
  - Сайт должен корректно отображаться на различных устройствах ( планшеты. смартфоны, ноутбуки, настольные компьютеры)
